apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: default
  annotations:
    # networking.gke.io/load-balancer-type: "Internal"
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: foo
  ports:
  - name: http
    port: 80
    targetPort: 8080