apiVersion: v1
kind: Service
metadata:
  name: whereami
  namespace: whereami
  annotations:
    configmanagement.gke.io/cluster-selector: dev-cluster-selector
spec:
  selector:
    app: whereami
  ports:
  - port: 8080
    targetPort: 8080
    appProtocol: http
    name: http-access