helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.5.3
  releaseName: my-cert-manager
  namespace: my-cert-manager
  includeCRDs: true
  valuesFile: values.yaml
  valuesInline:
    replicaCount: 567