apiVersion: v1
kind: ConfigMap
metadata:
  name: dynatrace-gcp-monitor-cm
  namespace: config-management-system
immutable: true
# You can use the same format as the default values file to override
# default values.
data:
  values.yaml: |-
    image:
      pullPolicy: Always
    primary:
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi