apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync-oci
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    # repo: oci://${REGION}-docker.pkg.dev/${PROJECT}/${CONTAINER_REGISTRY_NAME}
    repo: oci://us-central1-docker.pkg.dev/cn-datahub-logs/oci-artifacts
    chart: dynatrace-gcp-monitor
    version: 0.3.0
    releaseName: dynatrace-gcp-monitor
    namespace: default
    auth: gcpserviceaccount
    gcpServiceAccountEmail: oci-artifacts-reader@cn-datahub-logs.iam.gserviceaccount.com